
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Content Style Guide
description: >
  Simpler, clearer, faster.
  Content guide for Australian Government.

baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site

gems: [bourbon,neat]

assets:
  compress:
    css: true
    js: true
  cache: .asset-cache
  prefix: "/cdn"
  digest: true

sass:
  sass_dir: _sass

collections:
- entries

# Build settings
markdown: kramdown

prose:
#  rooturl: ''
  siteurl: 'http://gov.au/alpha'
  ignore:
    - _config.yml
    - /manifest.yml
    - /circle.yml
    - /_assets
    - /_data
    - /_layouts
    - /_includes
    - /_plugins
    - /_posts
    - /assets
    - /bin
    - /fonts
    - /css
    - /js
    - /Staticfile
    - /Staticfile.auth
    - /Gemfile
    - /Gemfile.lock
    - /.ruby-version
    - /.gitignore
    - /feed.xml
    
exclude:
  - vendor/
