
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Content Style Guide
description: >
  GOV.AU content meets our users’ needs. It works for everyone, regardless of
  ability. We aim for the fewest and clearest words possible to explain what
  people need to know.

baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site

collections:
- entries

# Build settings
markdown: kramdown

prose:
  rooturl: '/'
  siteurl: 'http://gov.au/alpha'
  ignore:
    - _config.yml
    - /_assets
    - /_data
    - /_layouts
    - /_includes
    - /_plugins
    - /assets
    - /bin
    - /fonts
    - /_posts
    - /css
    - /js
    - /Staticfile
    - /Staticfile.auth
    - /manifest.yml
    - /circle.yml
    - /Gemfile
    - /Gemfile.lock
    - /.ruby-version
    
exclude:
  - vendor/
