# Jekyll configuration for the GOV.AU Content Style Guide
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings.
title: Draft Content Style Guide
version: "1.0"
description: >
  Simpler, clearer, faster.<br>
  A draft content style guide to help government meet the needs of all users, regardless of their ability.

baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site

gems: [bourbon,neat]

assets:
  compress:
    css: true
    js: true
  cache: .asset-cache
  prefix: "/cdn"
  digest: true

sass:
  sass_dir: _sass

# Global Collection settings.
defaults:
  - scope:
      path: ""
      type: writing-for-the-web
    values:
      layout: collection-item
      permalink: /:collection/:title

collections:
  entries:
    title: "A to Z"
    output: true
  writing-for-the-web:
    title: "Writing for the web"
    output: true
  sources:
    title: "Sources for this guide"

# Markdown build settings.
markdown: kramdown

# Config for htt://prose.io editor.
prose:
#  rooturl: ''
  siteurl: 'http://gov.au/alpha'
  ignore:
    - _config.yml
    - /manifest.yml
    - /circle.yml
    - /_assets
    - /_data
    - /_layouts
    - /_includes
    - /_plugins
    - /_posts
    - /assets
    - /bin
    - /fonts
    - /css
    - /js
    - /Staticfile
    - /Staticfile.auth
    - /Gemfile
    - /Gemfile.lock
    - /.ruby-version
    - /.gitignore
    - /feed.xml

# Files to exclude from jekyll builds.
exclude:
  - vendor/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - Rakefile
